- content/docs/components-and-props.md
- content/docs/introducing-jsx.md
- content/docs/lists-and-keys.md
I fixed some translation and sync terms.
> fix(docs): wording and sync terms

- content/tutorial/tutorial.md
Fix conflicts from merged pull request #29.
Thanks. @neighborhood999
> Fix conflicts in tutorial

- content/docs/hooks-intro.md
> doc: translate hooks-intro

- content/docs/getting-started.md
This PR is ready for review!
I kept the following words untranslated:
`ecosystem`
`widget`
And I am not sure about translating
`dynamic` to `可變`
> doc: Translate Getting Started

- content/docs/addons-shallow-renderer.md
Keep the following words:
- shallow renderer
- shallow rendering -> shallow render
- child (component)
- assert
> doc: translate shallow renderer

- content/docs/composition-vs-inheritance.md
Below are the terms and I'm not sure how to translate:
- composition
- containment (I translate `包含`)
- specialization (I translate `特別化`)
> docs(tw): translanslate composition-vs-inheritance

- content/docs/add-react-to-a-website.md
> doc: update add react to a website

- content/docs/nav.yml
- content/docs/reference-glossary.md
translate the [glossary page](https://reactjs.org/docs/glossary.html)
maybe @chloewlin can help to label it in #1 ? thanks!
<details>
<summary>Click to view screen capture</summary>
</details>
> docs: translate glossary

- content/docs/cdn-links.md
This PR is ready for review. Thanks!
> doc: translate cdn links

- content/docs/handling-events.md
Synchronize my local branch and set up PR so that folks know I am working on handling events!
> Set up PR for translating handling events

- content/docs/hooks-state.md
>  doc: translate hooks-state

- content/tutorial/nav.yml
Since I translated the tutorial, I am going to finish nav as well. ;) Everything is consistent with `tutorial.md`.
> Set up tutorial branch

- content/docs/addons-test-utils.md
- content/docs/code-splitting.md
- content/docs/nav.yml
- content/docs/reference-test-renderer.md
- src/components/LayoutFooter/Footer.js
> Fix conflict in sync-ddbd064d

- content/docs/hooks-faq.md
> docs(hooks): translate hook faq

- content/docs/jsx-in-depth.md
Noticed a small mistake made during the revision in #102 .
> Hot fix docs: JSX in Depth 

- content/docs/web-components.md
doc: translate web components to zh-hant
> doc: translate web components to zh-hant

- content/docs/reference-dom-elements.md
Found in the [reference-dom-elements](https://github.com/reactjs/zh-hant.reactjs.org/blob/master/content/docs/reference-dom-elements.md) docs.
> fix: remove unvisible symbol

- content/docs/hooks-faq.md
> docs(hooks): wording

- content/docs/reference-react-component.md
compare with english version.
https://reactjs.org/docs/react-component.html#componentwillunmount
it should talking about componentWillUnmount
> Correct mention wrong methond name

- content/docs/refs-and-the-dom.md
> translate refs and the dom

- content/docs/reference-react-component.md
> correct docs(reference-react-component) typo

- content/tutorial/tutorial.md
as title.
See [here](https://deploy-preview-129--zh-hant-reactjs-org.netlify.com/tutorial/tutorial.html#help-im-stuck) for result after this PR.
> [Tutorial] Add a space in between

- content/docs/lifting-state-up.md
> docs(lifting-state-up): second input translation

- content/docs/lists-and-keys.md
> docs(lists-and-keys): original text: numbers array

- content/docs/state-and-lifecycle.md
> 補上一個 backtick

- content/docs/components-and-props.md
> Fix the conflict in doc/components-and-props.md

- content/docs/hooks-faq.md
> Fix a typo in FAQ

- content/docs/hooks-faq.md
發起 is not too idiomatic. It means initiate, launch, originate. So 發起 一個 issue means "initiate an issue", "launch an issue", "originate an issue".
提出 sounds more right. It means bring out, put forward, raise. 提出一個 issue means "bring out an issue", "put forward an issue", "raise an issue".
> 提出 sounds more right

- content/docs/hooks-faq.md
> Fix typo in faq doc

- content/docs/rendering-elements.md
> docs(rendering-elements): wording

- content/docs/hooks-state.md
"class state" was used together
> docs(hooks-state): wording

- content/docs/faq-state.md
> docs(faq): translate faq-state

- src/css/reset.css
- yarn.lock
Trying fix netlify build error...
> chore: re-gen yarn.lock

- content/docs/handling-events.md
remove meaningless word and garbled text in doc/handling-events.md
> Remove meaningless word and garbled text

- content/tutorial/tutorial.md
> Fix some typos

- content/docs/hooks-rules.md
Translated a short sentence as I spotted while I read.
Hope it helps.
> Translate description of CRA regarding eslint plugin

- content/docs/state-and-lifecycle.md
> fix typo in state-and-lifecycle.md

- content/docs/accessibility.md
Setting up a PR for my upcoming translation in Accessibility.
> Accessibility

- content/docs/getting-started.md
> fix a conflict in `getting-started`

- content/docs/hooks-custom.md
> Correct typo

- beta/src/pages/learn/start-a-new-react-project.md
- Translation beta document - start a new react project
> docs: translation start a new react project

- beta/src/pages/learn/add-react-to-a-website.md
> docs: translation add react to a project

- content/docs/uncontrolled-components.md
> Remove the redundant full stop in Uncontrolled Component section

- beta/src/pages/learn/editor-setup.md
> feat: translate editor setup

- content/tutorial/tutorial.md
> Docs: remove git conflict content

- content/docs/hello-world.md
> fix(docs): codepen broken link

- content/docs/forms.md
> Docs: fix typo

- content/docs/render-props.md
> Docs: remove redundant text

- content/docs/reference-react-dom.md
- content/docs/reference-react.md
- content/docs/strict-mode.md
> fix: resolved conflict

- src/html.js
HTML lang attr `en` -> `zh-Hant`
> Update html language code (zh-Hant)

- content/docs/reference-events.md
> translate-onFocus

- content/docs/lists-and-keys.md
> fix: typo of link, ttps -> https

- src/content/learn/add-react-to-an-existing-project.md
> feat: translate add react to an existing project

- src/content/learn/index.md
> feat: translation quick-start

- src/content/learn/rendering-lists.md
Hi, Please let me know if any problem I need to fix.
Thank you !
> docs: translation Rendering Lists

- src/content/learn/rendering-lists.md
> fix: redundant space

- src/content/learn/conditional-rendering.md
- src/content/learn/javascript-in-jsx-with-curly-braces.md
- src/content/learn/rendering-lists.md
- src/sidebarLearn.json
> chore: translate sidebar items

- src/content/reference/react/useOptimistic.md
finish incomplete merge-conflict-fix in `/src/content/reference/react/useOptimistic`
> finish incomplete merge-conflict-fix in `/src/content/reference/react/useOptimistic`

- src/content/learn/start-a-new-react-project.md
> fix: start a new react project translation
