content/docs/faq-ajax.md
This Pull Request translates [AJAX and APIs](https://reactjs.org/docs/faq-ajax.html) page:
```
git clone git@github.com:reactjs/zh-hant.reactjs.org.git
git am -3 https://github.com/reactjs/zh-hant.reactjs.org/pull/3
yarn dev 
open http://localhost:8000/docs/faq-ajax.html
```
<details>
<summary><kbd>Click to view translated page from this Pull Request</kbd></summary>
</details>
See the tracking issue of progress: https://github.com/reactjs/zh-hant.reactjs.org/issues/1
=> docs(zh-hant): Translate FAQ: AJAX and APIs

content/docs/rendering-elements.md
Here are some term not sure to translate or not, so I didn't translate its:
- Rendering
- Elements
- Component
- root
- node
- attribute
- tree
=> docs(tw): translate rendering elements

content/docs/components-and-props.md, content/docs/nav.yml
This Pull Request translates [Components and Props](https://reactjs.org/docs/components-and-props.html) page.
<details>
<summary><kbd>Click to view translated page from this Pull Request</kbd></summary>
</details>
See the tracking issue of progress: https://github.com/reactjs/zh-hant.reactjs.org/issues/1
=> docs(zh-hant): Translate Components and Props

content/docs/state-and-lifecycle.md
This tech terms I keep the original:
- local state
- destroy
- merge
- shallow
=> docs(tw): translate state-and-lifecycle

content/docs/introducing-jsx.md, content/docs/nav.yml, examples/introducing-jsx.js
This one is pretty hard because there're a lot of overloaded terms: React elements v.s. HTML elements etc. I try to stick to the glossary as to what to translate and what to keep in English.
Let me know if I missed anything or any feedbacks! :smile:
=> docs(zh-hant): introducing jsx

content/docs/conditional-rendering.md, content/docs/nav.yml
This PR translate the [Conditional Rendering](https://reactjs.org/docs/conditional-rendering.html) page.
<details>
<summary>Click to screen capture</summary>
</details>
=> doc: translate conditional rendering

content/docs/reference-react.md
Translation for the React API in the API reference section. There are some very convoluted sentences in the notes, I've tried my best translating them but suggestions are welcomed! :pray:
=> [api] react

content/docs/nav.yml, content/docs/reference-javascript-environment-requirements.md
translate the [js environment requirement page](https://reactjs.org/docs/javascript-environment-requirements.html)
I'm not quite sure do we want to translate the word `package` and `shim`, now I keep them in English
again @chloewlin could you help to label in #1 , thanks 🙇 
<details>
<summary>Click to view screen capture</summary>
</details>
=> docs: translate js environment requirement

content/community/conferences.md, content/docs/hooks-intro.md, content/docs/hooks-overview.md, content/docs/nav.yml, src/components/LayoutFooter/Footer.js
Ready to review!
I made an independent PR for each article for easier merging.
I will keep doc: Translate Hooks #32 open until all the Hooks topics are done.
I will track the Hooks translation progress there, which will be friendly for newcomers following current progress.
Also, I find it hard to avoid my hooks-intro.md work. Please cherry-pick hooks-overview.md commits in this PR and I will pull the result on master and start from there on my next translation.
Let me know if you have any thought!
Update: I have resolved conflict on hooks-intro.md by deleting my part. This PR should have no collision with the master branch now.
=> doc: translate hooks-overview

content/docs/thinking-in-react.md
Hi, this is my work on `thinking in react`. A few words I am not sure of: 
- affordance
- modular 模塊化/模組化
- implement 實作
- react doc 文件
- representation 
- checkbox 複選框 
- attribute / property 
- callbacks
=> doc: complete think in react

content/docs/add-react-to-a-website.md
This PR is ready for review!
I left these untranslated:
- ``bundler``
- ``preprocessor``
- ``composition``
And I'm not sure translating ``production`` to ``正式發佈``.
The translation (生产环境) for it in Simplified Chinese feels kind of awkward to me.
=> doc: translate add react to a website

content/docs/reference-test-renderer.md
Keep the following words:
- descendant
- function component
- snapshot
- assert
I translated the following words:
- test instance: 測試 instance
- re-mount: 重新 mount
- throw an error: 拋出錯誤
- mock: 模擬的/模擬
- idea: 概念
Welcome to discussed about these words.
=> doc: translate Test Renderer

content/docs/reference-dom-elements.md
Besides words mentioned in [Glossary](https://github.com/reactjs/zh-hant.reactjs.org/wiki/Glossary), I remain these untranslated.
- `server`/`client` (side)
- `style`
- `timestamp`
- `key`
- `property`
- `pixel`
- `camelCase`
- `controlled component`
Welcome for further discussion.
=>  doc: translate dom-elements

content/docs/create-a-new-react-app.md
=> doc: translate create a new react app

content/docs/addons-test-utils.md
Translations of some words are not consistent in API Reference:
- overview (`概觀` or `概覽`)
- reference (`參考`, `參考資料`, or no translation)
Terms I don't translate:
- boilerplate code
- dispatch
I'm not sure how to translate:
- We recommend using [`react-testing-library`](https://git.io/react-testing-library) which is designed to enable and encourage writing tests that use your components as the end users do. (Line 22)
- ... a simple `<div>` containing any provided children. (Line 138)
`提供的` is weird.
- input field (Line 335)
=> doc: Test Utilities

content/docs/code-splitting.md
Not sure `Named Exports` how to translate, so keep the original term.
=> docs(code-splitting): translate code splitting

content/docs/hooks-rules.md
=> doc: translate hooks-rules

content/docs/handling-events.md
Hi all, here is my translation for `handling events`. Here are some terms I am not sure about: 
- `binding`/`bind`: I am using `綁定` here. I know some contributors don't like it, but I can't think of a better word for now. It also feels weird to use the English word. I am open to suggestions.
- `listener`:  not sure how to translate it. 
- `event handler`:  not sure how to translate it. Sometimes I just refer to it as `事件`.
=> docs: Handling events

content/docs/reference-react-dom-server.md
=> docs: ReactDOMServer

content/docs/hooks-reference.md
Done.
~Not finished all, create this draft PR to kickstart review first.~
TODO:
=> docs: translate hooks API reference

content/docs/fragments.md
Follow the existing translation pattern and translate Fragments.md, feel free to let me know if there is any problem, thank you.
=> docs: translated Fragments.md

content/docs/reconciliation.md
Translate Reconciliation.md. Thanks to @chentsulin for kindly reading the draft. 
Feel free to let me know if there's any suggestion.
=> docs: Reconciliation

content/docs/jsx-in-depth.md
Please let me know if you have any suggestion and if any revision can be made.
=> docs: JSX in Depth

content/docs/hello-world.md, content/docs/introducing-jsx.md, content/docs/rendering-elements.md
I found some Codepen link text is `undefined` and removed the bold symbol. It can display correctly.
=> fix: remove * symbol avoid display undefined text

content/docs/uncontrolled-components.md
doc: translate uncontrolled components to zh-hant
=> doc: translate uncontrolled components to zh-hant

content/docs/strict-mode.md
doc: translate strict mode to zh-hant
=> doc: translate strict mode to zh-hant

content/docs/error-boundaries.md
translate error boundaries doc to zh-hant
=> doc: translate error boundaries to zh-hant

content/docs/hooks-effect.md
Sorry about the delay! The hooks-effect page is pretty long -- please let me know if I missed something and/or if you have any suggestions.
=> docs: hooks-effect

content/docs/forwarding-refs.md
=> Translate: Forwarding ref

content/docs/hooks-faq.md
Following glossary: `函式` -> `function`
=> fix(HooksFAQ): wording

content/docs/faq-build.md
=> docs(faq): translate faq-build

content/docs/hooks-faq.md
Origin text in English version is `testing components with Hooks shouldn’t be different from how you normally test components.`. It should be translate to `與你測試 component 的方式[相同]`.
=> Fix the wrong translation of the testing section in Hooks

content/docs/reconciliation.md
The old version link redirects user to
`https://zh-hant.reactjs.org/docs/(https://grfia.dlsi.ua.es/ml/algorithms/references/editsurvey_bille.pdf)`
And the webpage displays "Page Not Found".
=> Fix reconciliation link issue

content/docs/render-props.md
Call for help for these phrases/word below: 
1. Cross-Cutting Concerns (line 21)
2. reusable (current translation: *可重用*)
3. encapsulate (current translation: *封裝*)
Please feel free to make comments or suggestion for the other parts as well. Thanks!
=> docs: translate Render Props

content/docs/reference-react-component.md
`fully controlled` shouldn't be the same as `fully uncontrolled`.
reference from [here](https://github.com/reactjs/zh-hant.reactjs.org/blob/master/content/docs/uncontrolled-components.md#L44). 「不可」
=> fix `uncontrolled` translations

content/docs/hooks-reference.md
Fix a tiny typo in [Hooks API Reference](https://github.com/christopher0404/zh-hant.reactjs.org/blob/master/content/docs/hooks-reference.md#uselayouteffect-uselayouteffect)
廷遲 → 延遲
=> Fix typo in hooks-reference.md

content/docs/portals.md
Translate Advanced guides - `Portals`
=> docs(Advanced guides): Translate Portals

content/docs/faq-styling.md
Hi, sorry for the mistake in the last PR.
Please feel free to make any edit! Thanks!
=> docs: translate `faq-styling`

content/docs/hooks-effect.md
自訂 is more appropriate. It means custom or customized.   自定義 means self-defining or self-defined and it is too heavy.  It is not "self defining" but is self-defined and It just means a custom message. In fact, it could have been 我們把網頁標題設定為包含點擊次數的訊息。
The word "custom" is not even needed, because we are saying "we set it to a message that includes the number of clicks", and the meaning of "custom" is very apparent.  We could use the word 自訂 if we want to stick to the original English sentence as close as possible.
=> 自訂 is more appropriate

content/docs/hooks-effect.md
你有*很多*可以去做 is "You have a lot can go do" doesn't sound right.
The English version is "there is a lot you can do with both of them combined"
it means:
把兩者結合起來，你已經能做到很多東西。
combining both, you already can do a lot of things.
你有*很多*可以去做 is "You have a lot can go do"  or "You have a lot can do"  They don't sound right.
The English version has "a lot" in italic, so it is done for the translation as well, for 很多.
=> 你有*很多*可以去做 is "You have a lot can go do"

content/docs/react-without-es6.md, content/docs/react-without-jsx.md
Translate Advanced guides - `React without ES6`
=> docs(Advanced guides): React without ES6

content/docs/hooks-faq.md
I found my translation is not correct also includes a typo.
=> fix(hooks-faq): typo and wording

content/docs/hooks-custom.md
Fixed `想是` -> `像是`
Also ad-hoc may not be understandable for some traditional Chinese readers.
=> Fix typo in useYourImagination() section

beta/src/pages/learn/react-developer-tools.md, beta/src/sidebarLearn.json, content/docs/add-react-to-a-website.md
=> feat: translate react dev tools 

content/docs/reference-react.md
=> docs: translate contents

beta/src/pages/learn/describing-the-ui.md, beta/src/sidebarLearn.json
https://zh-hant-beta-reactjs-mzerspb9y-fbopensource.vercel.app/learn/describing-the-ui
#260
=> feat: translate describing the ui

content/docs/testing.md
=> Docs: fix typo

content/docs/reference-glossary.md
Improve the translation of [Keys](https://zh-hant.reactjs.org/docs/glossary.html#keys) in the "Glossary of React Terms" and fix typos.
=> Improve the translation of Keys in the Glossary

beta/src/content/learn/javascript-in-jsx-with-curly-braces.md
Translation beta document - JavaScript in JSX
=> docs: translation JavaScript in JSX

src/content/learn/start-a-new-react-project.md
=> feat(docs): translate start a new react project

src/content/learn/react-developer-tools.md, src/sidebarLearn.json
- chore: translate get started sidebar
- chore: wording
=> chore: translation sidebar and docs wording

src/content/learn/render-and-commit.md
Hi ! I translate Render and Commit. Could you please review it and let me know your feedback ? Thanks !
=> docs: translation Render and Commit

src/content/learn/responding-to-events.md
Rephasing the wording in Section Responding to Events, the original statement sounds a bit off to me:
像 `onPlayMovie` 這樣依據特定應用互動命名的 prop 讓你有彈性在之後改變它們的使用方式
像 `onPlayMovie` 這樣依據特定應用互動命名的 prop 讓你在以後更改其使用方式時具有彈性
The revised version provides smoother grammar while retaining the original meaning
=> docs: Refine Wording in "Responding to Events" Section

src/content/learn/importing-and-exporting-components.md
=> translation: Importing And Exporting Components

src/content/learn/your-first-component.md
=> translation: Your First Component

src/content/learn/removing-effect-dependencies.md, src/content/learn/reusing-logic-with-custom-hooks.md
=> fix: resolved conflicts
